---
title: "로지스틱 회귀"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r }
data("iris")
a <- subset(iris, Species == "setosa" | Species == "versicolor")
a$Species <- factor(a$Species )
str(a)
## 회귀계수의 검정에서 p-값이 거의 영(0)이므로 Sepal.Length가 매우 유의한 변수이며, ## Sepal.Length가 한 단위 증가함에 따라 versicolor(Y=2)일 오즈가 exp(5.140)≈170배 증가함을 알 수 있다.
b <- glm(Species~Sepal.Length, data=a, family=binomial)
summary(b)
## Residual deviance는 예측변수 Sepal.Length가 추가된 적합 모형의 이탈도를 나타낸다. Null deviance에 비해 자유도 1 기준에 이탈도의 감소가 74.4 정도의 큰 감소를 보이며, 􀝌-값= 􀜲(􀝔􀬶 98 > 64.211) ≈ 0.997 이므로 귀무가설(적합 모형)이 기각되지 않으며 적합값이 관측된 자료를 잘 적합하고 있다고 말할 수 있다.
coef(b)
exp(coef(b)["Sepal.Length"])

#predict() 함수를 이용하여 새로운 자료에 대한 예측을 수행한다. 여기서는 편의상 모형구축에 사용된 자료를 다시 사용한다.
predict(b, newdata=a [c(1, 50, 51, 100), ], type="response" )

#cdplot() 함수는 Sepal.Length(연속형 변수)의 변화에 따른 범주형 변수의 조건부 분포를 보여 준다. 아래의 그림은 Sepal.Length가 커짐에 따라 versicolor의 확률이 증가함을 보여준다. 이 함수는 로지스틱 회귀의 탐색적 분석에 유용하다.
cdplot(Species~Sepal.Length, data=a)


# 적합된 로지스틱 회귀모형의 그래프는 다음과 같다.

plot(a$Sepal.Length, a$Species, xlab="Sepal.Length")
x=seq(min(a$Sepal.Length), max(a$Sepal.Length), 0.1)
lines(x, 1+(1/(1+(1/exp(-27.831+5.140*x)))), type="l", col="red")

```